spring:
  profiles:
    active: dev
  redis:
    port: 6379
  servlet:
    multipart:
#      文件上传大小限制
      max-file-size: 2MB
      max-request-size: 10MB
#  # 静态资源路径
#  resources:
#    static-locations: classpath:static/,file:static/

#  设置响应为utf-8
  http:
    encoding:
      force-response: true

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#  druid:

server:
  port: 8088
  servlet:
    context-path: /ziyuan
  tomcat:
    uri-encoding: UTF-8
#   配置HTTP header默认缓冲区大小（不推荐使用的配置属性）（单位B）Byte
#   max-http-header-size: 8192

mybatis:
#  数据库映射实体类路径
#  typeAliasesPackage: com.wechat.recycle.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
#    开启驼峰映射
    map-underscore-to-camel-case: true
#    默认全局执行sql超时时间25秒，更细粒度请在具体方法上配置，单位秒
    default-statement-timeout: 25

pagehelper:
  helperDialect: mysql
  reasonable: false
  pageSizeZero: true
  supportMethodsArguments: true
  params: count=countSql;pageNum=pageNum;pageSize=pageSize;

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMCoaxZTPJ7
    stringOutputType: base64