spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recycle?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 31501370
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost