spring:
  profiles:
    active: dev

server:
  port: 8088
  servlet:
    context-path: /recycle-api-web
  tomcat:
    uri-encoding: UTF-8

mybatis:
#  数据库映射实体类路径
#  typeAliasesPackage: com.wechat.recycle.entity
  mapperLocations: classpath:mapper/*.xml

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMCoaxZTPJ7
